language: node_js
matrix:
  fast_finish: true
node_js:
- '16.18.1'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: npm
  email: npm@cozycloud.cc
  skip_cleanup: true
  api_key:
    secure: Uulm6pcJIJeIIyircLSF3O4AGmmlaojQhgC7DD2SlcYXAYAm8iUhDEC+FANMunAjWBTTzlqaO9IOpRKbUGrYZKt64GMrleS320ZH3iyBAk6QaZ0vs6ko5OkxizjpjXZZqd15FQn1kQXfbTAYy7A5ganwcWJNIx/Rz947DMsnTcWk76Ihbak+YPBX9eWisl+MGueFyGzng/JVuerV2DPnHYi8GdqxuldIX8KSLtBXMFu0CU/hVQdE4ktszK5ZmLK8/gza5JJyUo7fIRDabO51mJ3AfJtBWSzSQ+5F76iHGeQHxbo/9bAy9Ss5zfC+dArdSkQwOEmo4i2+Zc9ZNRjSjyHYtMGzHqwMOnWZi48p/TeQwP1Zua0RusKTEtsrnO167uF7nk6IXeOGp9kT2PrJ1fj704AkyO0YM3YGOZdcHi1anQYKlg512KTd7kSXptVlEyDBSpVN2EEfB8T7PtH96V5MPsQbLqh6hO0WjiDir0RvrR33jKsZ0emm0q+0XYi5cSE4lbn9tru36lKHhqMCQQ4bVZtdS/FiKjzWYi1+L+3iCYNK8DMeyq/4Xh8QusxjmbF817OFR57Rvq8pzrdkWHlmJfYvjjzGW5hm9fwJEP7B04fqSTa4X7LCSPlmTIHKgoQDMqELXRXoseCaQedLWVqpRM2jYN6p6H3p1ZPGiW8=
  on:
    tags: true
    repo: konnectors/konitor
    branch: master
